server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      # globalcors 설정 제거: Nginx Proxy 사용으로 Same-Origin 정책 적용됨
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: challenge-service
          uri: http://challenge-service:8082
          predicates:
            - Path=/api/v1/challenges/**
        - id: ai-service
          uri: http://ai-service:5000
          predicates:
            - Path=/api/v1/ai/**
