spring:
  datasource:
    url: jdbc:mysql://192.168.219.108:3306/fit_challenge_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: user
    password: kho13241003567
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true # 데이터 초기화 스크립트 실행 지연
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  data:
    redis:
      host: 192.168.219.108
      port: 6379
  kafka:
    bootstrap-servers: 192.168.219.108:9092
    consumer:
      group-id: challenge-group
      auto-offset-reset: earliest
  sql:
    init:
      mode: always # data.sql 실행 활성화
  lifecycle:
    timeout-per-shutdown-phase: 10s

server:
  shutdown: graceful

logging:
  level:
    com.fit.challenge: DEBUG
